### ISSUE TITLE
Do not use babel-polyfill

### ISSUE THREAD

**Issue by puco** [red5pro/streaming-html5#108]
When including your SDK in an app that already uses babel-polyfill the loading of SDK is not successful. Based on [https://github.com/babel/babel/issues/4019] and [https://babeljs.io/docs/usage/polyfill/#details] libraries should not use babel-polyfill.

Repo steps:
- Load `babel-polyfill`
- Load `red5pro-sdk`

Expected result:
- Page and SDK are working

Actual result:
- `Uncaught Error: only one instance of babel-polyfill is allowed`

**Comment by bustardcelly** [comment]
should be fixed in v4.0.0 of the SDK. Download available https://account.red5pro.com/download
