### ISSUE TITLE
Can't join red5pro slack channel

### ISSUE THREAD

**Issue by cupuyc** [red5pro/streaming-html5#128]

**Comment by gharia** [comment]
Were you able to join? I am not getting any invite and joining using my google account just keep failing

**Comment by cupuyc** [comment]
Yes. But I don't remember if invite came within 24h or I asked for the invitation via a different communication channel.

**Comment by gharia** [comment]
Yeah, the invite came after couple of hours for me. I am able to join now. Thanks. I was expecting an invite to be automated!!

**Comment by beetlejesss** [comment]
Hi All - the slack invite process is manual - so, depending on what time of day you send the request you may get a fast response or it may take a couple of days if you request over the weekend.
