### ISSUE TITLE
Not working in live server

### ISSUE THREAD

**Issue by ManojPadhiyar** [red5pro/streaming-html5#214]
Hello,
I trying in localhost it working properly but when i upload in server it's not working
Please suggest better solution. 
Thank you 👍 :)

**Comment by HoldenMills** [comment]
Hello Manoj. Please provide our support team with more information by submitting a ticket using this link: https://red5pro.zendesk.com/hc/en-us/requests/new.
Please make sure to provide additional details such as reproduction steps and specific devices used to speed up the process.
