### ISSUE TITLE
NPM installation 

### ISSUE THREAD

**Issue by tillkruss** [red5pro/streaming-html5#49]
Could you guys add the HTML5 WebRTC js SDK to npmjs.com?

**Comment by beetlejesss** [comment]
This is on our roadmap! 
hey, @bustardcelly :)

**Comment by tillkruss** [comment]
Any updates on this? It's been 3 months and there is no way of knowing when a new HTML5 SDK is released.

**Comment by puco** [comment]
After 9 months: What is the status on this?

**Comment by beetlejesss** [comment]
This is still on our long-term roadmap, but has taken a back seat to features and bugfixes. We will be implementing this along with the public release of our HTML5 SDK source code; some time after release 4.0.0.

**Comment by sara3988** [comment]
hello, any updates on this?

**Comment by xtrasmal** [comment]
any updates on this? Frontend-land is moving pretty fast and the whole paradigm is focussed on small packages, imported through es6 modules. Using window or globals is like using dial-up modems to connect to the internet.

**Comment by alexsorokoletov** [comment]
Any updates on this? This is active for last 3 years :) 
Not sure why open-sourcing the SDK is a dependency, you can pack it into NPM without open-sourcing.
Also, it would be nice to include Typescript typings (probably a separate feature request)

**Comment by Kaishiyoku** [comment]
Any news for this?

**Comment by varadig** [comment]
just for fun... any updates on this?... I don't tink so

**Comment by PrinceTi** [comment]
Any update for this?

**Comment by bwoodlt** [comment]
Any update on this??

**Comment by bustardcelly** [comment]
With the release of `Red5 Pro 8.0.0`, we have published the build of Red5 Pro WebRTC SDK to NPM!

[https://github.com/red5pro/red5pro-webrtc-sdk](https://github.com/red5pro/red5pro-webrtc-sdk)

You can install the SDK in your projects via:

npm:

```sh
npm install --save red5pro-webrtc-sdk
```

yarn:

```sh
yarn install red5pro-webrtc-sdk
```

---

Additionally, you can include the script on your page from the `jsdelivr` CDN:

```html
<script src="https://cdn.jsdelivr.net/npm/red5pro-webrtc-sdk@8.0.0/red5pro-sdk.min.js"></script>
```

---

Thank you all for your patience and patronage and happy streaming!
