### ISSUE TITLE
Can we save Video in Mp4 Format?

### ISSUE THREAD

**Issue by bhawin-bigstep** [red5pro/streaming-html5#66]
Hi Red5pro,

I have been using red5pro and i am very satisfied with it.

I just have a doubt.
Can we save the video in mp4 format without ffmpeg.

I mean can broadcast be directly stored as mp4 file rather than flv ?

**Comment by HoldenMills** [comment]
Glad to hear you have been satisfied.  You cannot save directly to mp4.  You have to convert the flv to mp4 post process.
